### ISSUE TITLE
Unable to view A17 and A18 in TunerStudio for DropBear

### ISSUE THREAD

**Issue by Rozakiin** [speeduino/Hardware#21]
In dropbear v2 ecu the spare Analog outputs are A17 and A18 but in TunerStudio the dropdown only goes to A16.

Not sure if this is a software issue or label issue of the PCB?

**Comment by Rozakiin** [comment]
Upon further investigation this is due to the Speeduino ini file not listing the pins available for teensy. Therefore not relevant to the hardware.

https://github.com/speeduino/speeduino/issues/1191

This issue relates to the problem.

**Comment by noisymime** [comment]
There are quite a few changes coming in the next release that will be adding support for a few things on Dropbear v2, this will be one of them.

Expecting this release out before Christmas.
