### ISSUE TITLE
Resistors 25 27 31 32

### ISSUE THREAD

**Issue by AmesisProject** [speeduino/Hardware#8]
Hello, I just noticed that a resistor is missing on the kicad version before the ignition output on the 0.4.3d file
While this resistance is on all the other files as well on the 0.3x 0.4x fritzing as the kicad CMS.
Is this normal? I can fix it and do a pullrequest on GitHub if you want it

![d](https://user-images.githubusercontent.com/57772906/201636572-b2b6d5b5-a7d6-40b8-91ef-67d3e6f99b16.jpg)

**Comment by turboedge** [comment]
Josh did some testing actually, and decided that those resistors were not required. So they were not included in newer versions.

**Comment by noisymime** [comment]
Per comments on Facebook, those resistors are not required.
